---
- name: Install Debian packages
  become: yes
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - make
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
  when: nodejs_install_source == 'build'
